export const ROLES = {
  STAFF: 'STAFF',
  DEPT_HEAD: 'DEPT_HEAD',
  CEO: 'CEO',
  SUPERADMIN: 'SUPERADMIN',
};

export const FILE_STATUS = {
  DRAFT: 'DRAFT',
  DEPT_HEAD_REVIEW: 'DEPT_HEAD_REVIEW',
  CEO_REVIEW: 'CEO_REVIEW',
  APPROVED: 'APPROVED',
  RETURNED: 'RETURNED',
};

export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  RETURNED: 'RETURNED',
};

export const GATE = {
  DEPT: 'DEPT',
  CEO: 'CEO',
};

export const PRIORITY = ['LOW', 'NORMAL', 'HIGH', 'URGENT'];
export const SECRECY = ['OPEN', 'INTERNAL', 'CONFIDENTIAL', 'SECRET'];

export const ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FILE_CREATED: 'FILE_CREATED',
  NOTE_ADDED: 'NOTE_ADDED',
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  DEPT_APPROVED: 'DEPT_APPROVED',
  CEO_APPROVED: 'CEO_APPROVED',
  FILE_RETURNED: 'FILE_RETURNED',
};

export const SYSTEM = {
  UPLOAD_DIR: 'uploads',
  MAX_FILE_MB: 25,
};